#Setup
title: Luke Storry
tagline: Computer Science student at the University of Bristol.
description: Luke Storry's Homepage, Blog, Portfolio and list of links
baseurl: "" # the subpath of your site, e.g. /blog
paginate:     1

# About/contact
author:
  name: Luke Storry
  url: "http://LukeStorry.co.uk"
  email: Luke@LukeStorry.co.uk

email: Luke@LukeStorry.co.uk
twitter_username: LukeStorry
github_username:  LukeStorry
linkedin_username: LukeStorry
facebook_username: Luke.Storry
instagram_username: LukeStorry


# Build settings
markdown: kramdown
exclude: ["README.md"]
exclude: [vendor]
gems:
  - jekyll-paginate
